name: Check CNAME File Content

on: [push]

jobs:
  check-cname-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify CNAME content
        run: |
          CONTENT=$(cat ./CNAME)
          if [ "$CONTENT" != "richardvesely.com" ]; then
            echo "CNAME file does not contain exactly 'richardvesely.com'. Found content: '$CONTENT'"
            exit 1
          fi
